-- ============================================================================
-- ESTE FICHERO YA NO SE EJECUTA.
--
-- La fuente única del esquema es `supabase/migrations/`, que es el directorio
-- estándar de la CLI de Supabase:
--
--     supabase db reset      # base nueva, estado completo
--     supabase db push       # base ya desplegada
--
-- POR QUÉ SE RETIRÓ
--
-- Hubo un momento en que convivían este fichero y dos migraciones. Las
-- migraciones cerraron las políticas anónimas del chat y este fichero seguía
-- recreándolas con `using (true)`, así que volver a ejecutarlo deshacía la
-- seguridad entera. Con dos fuentes y un orden ambiguo, el estado final
-- dependía de en qué orden se hubieran ejecutado — que es exactamente lo que
-- no puede pasar con la seguridad.
--
-- Se conserva el nombre para que quien tuviera el camino en la cabeza o en un
-- script acabe aquí en vez de aplicar un esquema obsoleto.
--
-- El estado final vive en:
--     supabase/migrations/20260802000100_estado_seguro.sql
--
-- Y se comprueba instalándolo en un PostgreSQL de verdad:
--     npm run test:schema
-- ============================================================================
